name: dusza2019
description: Dusza 2019
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: 0.17.0

  animator: 1.0.0+2
  esys_flutter_share: 1.0.2
  # table_calendar: 2.1.0
  # dio_flutter_transformer: 2.0.10
  # dropdown_menu: 1.1.1
  url_launcher: ^5.0.2
  # uni_links: 0.2.0
  # font_awesome_flutter: 8.5.0
  toast: ^0.1.5

  # firebase_dynamic_links: 0.5.0+1
  flutter_auth_buttons: 0.5.0
  # firebase_analytics: 5.0.2
  # flutter_facebook_login: 3.0.0
  google_sign_in: 4.0.7
  firebase_auth: 0.14.0+5
  firebase_crashlytics: 0.1.0+3
  firebase_core: ^0.4.0+9
  # android_alarm_manager: 0.4.4
  dynamic_theme: 1.0.1
  auto_size_text: 2.1.0
  preferences: 5.0.1
  share: 0.6.3+1
  easy_localization: 1.3.1

  flutter_local_notifications: 0.8.4
  sticky_headers: 0.1.8
  package_info: 0.4.0+6
  font_awesome_flutter: 8.5.0


  equatable: 0.3.0
  flutter_bloc: ^0.20.0

  json_annotation: 2.3.0

  # dio: 2.1.13
  # connectivity: 0.4.3+6
  shared_preferences: 0.5.4+1

  cupertino_icons: ^0.1.2

  path_provider: ^1.1.0
  http: any
  uuid: any

dev_dependencies:
  build_runner: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: 2.3.0



flutter:
  uses-material-design: true
  assets:
    - assets/langs/en.json
    - assets/langs/hu.json
    - assets/images/

