name: dusza2019
description: Dusza 2019
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: 0.17.0
  flutter_launcher_icons: 0.7.4

  animator: 1.0.0+2
  url_launcher: ^5.0.2
  flutter_auth_buttons: 0.5.0
  google_sign_in: 4.0.7
  googleapis: 0.54.0
  firebase_auth: 0.14.0+5
  firebase_crashlytics: 0.1.0+3
  firebase_core: ^0.4.0+9
  dynamic_theme: 1.0.1
  auto_size_text: 2.1.0
  easy_localization: 1.3.1
  font_awesome_flutter: 8.5.0
  package_info: 0.4.0+10

  equatable: 0.3.0
  flutter_bloc: ^0.20.0

  json_annotation: 2.3.0

  shared_preferences: 0.5.4+1

  cupertino_icons: ^0.1.2
  csv: ^4.0.0

  path_provider: ^1.1.0
  http: 0.12.0+2
  uuid: 2.0.4
  intl: 0.16.0
  file_picker: 1.4.2

dev_dependencies:
  build_runner: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: 2.3.0

flutter_icons:
  image_path_android: "assets/images/elek.png"
  image_path_ios: "assets/images/elek.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"


flutter:
  uses-material-design: true
  assets:
    - assets/langs/en.json
    - assets/langs/hu.json
    - assets/images/

